import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import StoreProvider from '@/lib/storeProvider';
import './globals.css';
import React from 'react';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'CRS',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <StoreProvider>
                <body className={montserrat.className}>{children}</body>
            </StoreProvider>
        </html>
    );
}
