import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import React from "react";
import SessionProvider from "@/lib/next-auth/SessionProvider";
import AutoLogout from "@/lib/next-auth/AutoLogout";
import { Toaster } from "sonner";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SessionProvider>
          <AutoLogout>
            <main>
              {children}
              <Toaster position="top-center" />
            </main>
          </AutoLogout>
        </SessionProvider>
      </body>
    </html>
  );
}
