import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/app/globals.css';
import React from 'react';
import SideBar from '@/app/components/common/sidebar/Sidebar';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'CRS',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <section className="flex flex-col lg:flex-row">
                    <div className="lg:basis-[280px]">
                        <SideBar />
                    </div>
                    <div className="lg:basis-full p-6">{children}</div>
                </section>
            </body>
        </html>
    );
}
